# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GECalendarDemo (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GECalendarDemo (iOS)

end

target 'GECalendarDemo (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GECalendarDemo (macOS)

end
